name: Lint, format and test code
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**/*.py"

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          make install

      - name: Lint
        run: make lint

      - name: Format
        run: make ARGS="--check" fmt

      - name: Test
        run: make test