
name: Source code security scan using Bandit
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**/*.py"

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bandit
      run: |
        docker run --rm -v "$(pwd)":/data cytopia/bandit:latest -r /data -ll